language: node_js
node_js:
  - 'lts/*'
addons:
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves (for Cypress)
      - libgconf-2-4
cache:
  yarn: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache
install:
  - npm config set scripts-prepend-node-path true
  - yarn install --frozen-lockfile
jobs:
  include:
    - stage: Lint & Unit tests
      name: 'Lint'
      script: yarn lint
    - name: 'Unit Tests'
      script: yarn test:unit
      after_success:
        - |
          bash <(curl -s https://codecov.io/bash) -s 'packages/datagateway-common/*' -F common &&
          bash <(curl -s https://codecov.io/bash) -s 'packages/datagateway-dataview/*' -F dataview &&
          bash <(curl -s https://codecov.io/bash) -s 'packages/datagateway-search/*' -F search &&
          bash <(curl -s https://codecov.io/bash) -s 'packages/datagateway-download/*' -F download
    - stage: E2E Tests
      name: 'datagateway-download'
      script: yarn workspace datagateway-download run e2e
    - name: 'datagateway-search'
      script: yarn workspace datagateway-search run e2e
    - name: 'datagateway-dataview'
      script: yarn workspace datagateway-dataview run e2e
