language: node_js
node_js:
  - 'lts/*'
addons:
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves (for Cypress)
      - libgconf-2-4
cache:
  yarn: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache
install:
  - yarn install --frozen-lockfile
jobs:
  include:
    - stage: test
      name: 'Lint'
      script: yarn lint
    - name: 'Unit Tests'
      script: yarn test:unit
      after_success:
        - |
          bash <(curl -s https://codecov.io/bash) -s 'packages/datagateway-common/*' -F common &&
          bash <(curl -s https://codecov.io/bash) -s 'packages/datagateway-table/*' -F table &&
          bash <(curl -s https://codecov.io/bash) -s 'packages/datagateway-search/*' -F search &&
          bash <(curl -s https://codecov.io/bash) -s 'packages/datagateway-download/*' -F download
    - name: 'E2E Tests'
      script: yarn test:e2e
