name: Setup CI Build Environment
description: Setup Node.js and install or restore the required dependencies from cache

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    # Cache yarn dependencies/ restore the cached dependencies during future workflows
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: Cache yarn dependencies
      uses: actions/cache@v2
      id: yarn-cache
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install dependencies
      # Ubuntu 16+ does not install libgconf-2-4 by default, so we need to install it ourselves (for Cypress)
      run: |
        sudo apt-get install libgconf-2-4
        yarn --frozen-lockfile
