name: CI Build
on: [push, pull_request]

jobs:
  lint-and-unit-test:
    name: Lint & Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup environment
        uses: ./.github/actions/setup-environment
      - name: Run linting
        run: yarn lint
      - name: Run unit tests
        run: yarn test:unit
      - name: Upload unit test coverage for the Common package
        if: success()
        uses: codecov/codecov-action@v1
        with:
          directory: ./packages/datagateway-common/
          flags: common
          fail_ci_if_error: true
      - name: Upload unit test coverage for the DataView package
        if: success()
        uses: codecov/codecov-action@v1
        with:
          directory: ./packages/datagateway-dataview/
          flags: dataview
          fail_ci_if_error: true
      - name: Upload unit test coverage for the Search package
        if: success()
        uses: codecov/codecov-action@v1
        with:
          directory: ./packages/datagateway-search/
          flags: search
          fail_ci_if_error: true
      - name: Upload unit test coverage for the Download package
        if: success()
        uses: codecov/codecov-action@v1
        with:
          directory: ./packages/datagateway-download/
          flags: download
          fail_ci_if_error: true

  # Seperate e2e jobs so that they can run in parallel
  download-e2e-test:
    # Run only if the  Lint & Unit Tests job passed
    needs: lint-and-unit-test
    name: DataGateway Download End to End Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup environment
        uses: ./.github/actions/setup-environment
      - name: Run datagateway-download e2e tests
        run: yarn workspace datagateway-download run e2e

  search-e2e-test:
    # Run only if  the  Lint & Unit Tests job passed
    needs: lint-and-unit-test
    name: DataGateway Search End to End Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup environment
        uses: ./.github/actions/setup-environment
      - name: Run datagateway-search e2e tests
        run: yarn workspace datagateway-search run e2e

  dataview-e2e-test:
    # Run only if  the  Lint & Unit Tests job passed
    needs: lint-and-unit-test
    name: DataGateway DataView End to End Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup environment
        uses: ./.github/actions/setup-environment
      - name: Run datagateway-dataview e2e tests
        run: yarn workspace datagateway-dataview run e2e
