name: CI Build
on: [push, pull_request]

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Run linting
        run: yarn lint
      - name: Run unit tests
        run: yarn test:unit
      - name: Upload unit test coverage for the Common package
        if: success()
        uses: codecov/codecov-action@v1
        with:
          directory: ./packages/datagateway-common/
          flags: common
          fail_ci_if_error: true
      - name: Upload unit test coverage for the DataView package
        if: success()
        uses: codecov/codecov-action@v1
        with:
          directory: ./packages/datagateway-dataview/
          flags: dataview
          fail_ci_if_error: true
      - name: Upload unit test coverage for the Search package
        if: success()
        uses: codecov/codecov-action@v1
        with:
          directory: ./packages/datagateway-search/
          flags: search
          fail_ci_if_error: true
      - name: Upload unit test coverage for the Download package
        if: success()
        uses: codecov/codecov-action@v1
        with:
          directory: ./packages/datagateway-download/
          flags: download
          fail_ci_if_error: true
